SI-2322 Инициализация Retrofit
Pec3maker/SurfFilms pull request #3
Opened 2022-11-23 10:13 UTC by Pec3maker

2022-11-23 10:52 UTC, ValeraSetrakov requested changes

2022-11-23 10:52 UTC, ValeraSetrakov commented on base_feature/build.gradle
> +//    api project(":base_resources")
удаляем

2022-11-23 10:52 UTC, ValeraSetrakov commented on base_feature/build.gradle
> +    api retrofit.core
не должно находится в base_feature модуль, должно находится в commonInteractorModule

2022-11-23 10:52 UTC, ValeraSetrakov commented on base_feature/src/main/java/ru/surfstudio/filmssurf/application/network/di/NetworkModule.kt
> +@InstallIn(SingletonComponent::class)
надо перенести в i module

2022-11-23 10:52 UTC, ValeraSetrakov commented on base_feature/src/main/java/ru/surfstudio/filmssurf/application/network/di/OkHttpModule.kt
> +@InstallIn(SingletonComponent::class)
надо перенести в i module

2022-11-23 10:52 UTC, ValeraSetrakov commented on base_feature/src/main/java/ru/surfstudio/filmssurf/application/network/urls/MoviesUrls.kt
> +object Urls {
надо перенести в i module

2022-11-23 10:52 UTC, ValeraSetrakov commented on base_feature/src/main/java/ru/surfstudio/filmssurf/application/network/urls/ServerUrls.kt
> +object ServerUrls {
надо перенести в i module

2022-11-23 10:52 UTC, ValeraSetrakov commented on base_feature/src/main/java/ru/surfstudio/filmssurf/application/app/App.kt
> +@HiltAndroidApp
Давай попробуем перенести это в app модуль, не гарантирую, что сработает

2022-11-23 10:52 UTC, ValeraSetrakov commented on base_feature/src/main/AndroidManifest.xml
> +    <!--        android:label="@string/app_name"-->
удаляем

2022-11-23 10:52 UTC, ValeraSetrakov commented on base_feature/src/main/java/ru/surfstudio/filmssurf/application/app/di/AppModule.kt
> +object AppModule {
Давай попробуем перенести это в app модуль, не гарантирую, что сработает

2022-11-27 23:14 UTC, Pec3maker commented
![изображение](https://user-images.githubusercontent.com/38285312/204164839-e73058be-b8df-4cef-8f89-9247c2fed64f.png)
![изображение](https://user-images.githubusercontent.com/38285312/204164851-b83ef72b-d901-424c-ac37-c8e45433f0b1.png)
![изображение](https://user-images.githubusercontent.com/38285312/204164866-7d62a687-8f87-4a4f-9e82-c3800917a7e6.png)

2022-11-28 09:50 UTC, ValeraSetrakov requested changes

2022-11-28 09:50 UTC, ValeraSetrakov commented on config.gradle
> +            gson         : "com.google.code.gson:gson:${versions.gsonVersion}"
что за отступ?

2022-11-28 09:50 UTC, ValeraSetrakov commented on i_common/src/main/AndroidManifest.xml
> +<manifest package="ru.surfstudio.android.filmssurf.i_common" />
имена package нынче перекочевали в gradle соответствующего модуля

2022-11-28 09:50 UTC, ValeraSetrakov commented on base_feature/src/main/AndroidManifest.xml
> +<manifest package="ru.surfstudio.android.filmssurf.base_feature" />
имена package нынче перекочевали в gradle соответствующего модуля

2022-11-28 09:50 UTC, ValeraSetrakov commented on i_common/build.gradle
> +    api coroutines.core
думаю имеет смысл перенести это в commonModule.gradle

2022-11-29 15:22 UTC, ValeraSetrakov requested changes

2022-11-29 15:22 UTC, ValeraSetrakov commented on commonModule.gradle
> +    api coroutines.core
```suggestion
    implementation coroutines.core
```

2022-12-01 10:16 UTC, merged