Si 2323 load films module
Pec3maker/SurfFilms pull request #5
Opened 2022-11-30 08:39 UTC by Pec3maker

2022-12-02 11:08 UTC, ValeraSetrakov requested changes
Давай все кроме репозитория в i_common сделаем internal

2022-12-02 11:08 UTC, ValeraSetrakov commented on domain/src/main/kotlin/ru/surfstudio/films_surf/domain/models/Film.kt
> +data class Film(
давай добавим доку к полям и к классу

2022-12-02 11:08 UTC, ValeraSetrakov commented on i_common/src/main/java/ru/surfstudio/i_common/network/retrofit/dto/FilmListResults.kt
> +data class FilmListResults(
надо бы добавить к имени постфикс Response

2022-12-02 11:08 UTC, ValeraSetrakov commented on i_common/src/main/java/ru/surfstudio/i_common/network/retrofit/dto/FilmListResults.kt
> +data class FilmListResults(
по идее data добавлять не надо к ответам от сервера, так как мы не используем преимущества датаклассов, но при этом тратим время и место на их генерацию

2022-12-02 11:08 UTC, ValeraSetrakov commented on i_common/src/main/java/ru/surfstudio/i_common/network/retrofit/dto/FilmResponse.kt
> +data class FilmResponse(
по идее data добавлять не надо к ответам от сервера, так как мы не используем преимущества датаклассов, но при этом тратим время и место на их генерацию

2022-12-02 11:08 UTC, ValeraSetrakov commented on i_common/src/main/java/ru/surfstudio/i_common/network/repository/mapper/FilmResponseMapper.kt
> +            posterPath = input.posterPath,
давай тут добавим логику доработки путя до постера на сервере

2022-12-05 11:59 UTC, Maksim2355 approved these changes

2022-12-05 11:59 UTC, merged