SI-2325 init films screen clasess
Pec3maker/SurfFilms pull request #6
Opened 2022-12-02 10:29 UTC by Pec3maker

2022-12-02 11:32 UTC, ValeraSetrakov requested changes

2022-12-02 11:32 UTC, ValeraSetrakov commented on f_films/src/main/res/layout/activity_main.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
FragmentContainerLayout

2022-12-02 11:32 UTC, ValeraSetrakov commented on f_films/src/main/java/ru/surfstudio/f_films/MainActivityView.kt
> +        supportFragmentManager.commit {
эту команду нужно вызывать один раз, оберни в проверку на то, что savedInstanceState != null

2022-12-02 11:32 UTC, ValeraSetrakov commented on f_films/build.gradle
> +    implementation project(":base_feature")
давай перенесем подключение в commonFeatureModule

2022-12-05 12:46 UTC, Maksim2355 approved these changes

2022-12-05 12:46 UTC, Maksim2355 commented on f_films/src/main/java/ru/surfstudio/f_films/FilmsFragmentView.kt
> +        TODO("Not yet implemented")
Учитывай, что эти тудушки могут крашнуть прилу, если код сюда зайдет

2022-12-05 12:46 UTC, Maksim2355 commented on f_films/src/main/java/ru/surfstudio/f_films/FilmsFragmentView.kt
> +        return super.onCreateView(inflater, container, savedInstanceState)
Переопределять не нужно. Кстати, при наследовании от фрагмента, ему можно передать наш layoutRes

2022-12-06 09:21 UTC, Maksim2355 approved these changes

2022-12-06 09:21 UTC, Maksim2355 commented on f_films/src/main/java/ru/surfstudio/f_films/FilmsFragmentView.kt
> +    private val binding get() = _binding!!
Не особо понимаю смысла такого небезопасного вызова.

Мы можем ограничится нулабельным binding

Просто используя конструкцию binding?.run {}

плюс не забывай очищать биндинг

2022-12-07 12:21 UTC, merged