SI-2327 added films pagination and favourites
Pec3maker/SurfFilms pull request #7
Opened 2022-12-08 00:08 UTC by Pec3maker

2022-12-08 08:00 UTC, Maksim2355 requested changes

2022-12-08 08:00 UTC, Maksim2355 commented on base_feature/src/main/java/ru/surfstudio/base_feature/recycler/controller/PaginationFooterItemController.kt
> +                    showMoreBtn.visibility = View.VISIBLE
isVisibile?

2022-12-08 08:00 UTC, Maksim2355 commented on base_feature/src/main/java/ru/surfstudio/base_feature/recycler/controller/PaginationFooterItemController.kt
> +        private val loadingIndicator: ProgressBar =
[minor] На будущее, лучше заюзать/переписать на биндинги

2022-12-08 08:00 UTC, Maksim2355 commented on base_feature/src/main/java/ru/surfstudio/base_feature/recycler/film/FilmViewController.kt
> +        private val dateTv = binding.date
Какой смысл повторно создавать переменные и присваивать значения биндинга? Тогда смысл биндинга теряется

Лучше в том месте, где ты будешь юзать биндинг использовать with или run(если биндинг нуллабельный)

2022-12-08 08:00 UTC, Maksim2355 commented on base_feature/src/main/java/ru/surfstudio/base_feature/state/UiError.kt
> +        fun common(exception: Throwable): UiError =
Какое-то не очень говорящее название метода. Лучше назвать как-то по типу getUiError/...

2022-12-08 08:00 UTC, Maksim2355 commented on base_feature/src/main/java/ru/surfstudio/base_feature/recycler/controller/PaginationFooterItemController.kt
> +            showMoreBtn.visibility = View.GONE
Пс. На будущее. В верстке должно быть изначальное состояние. А для того, чтобы смотреть превью, ты можешь прописать tools:visibility

Ибо возникает неопределенное поведение. Представь, есть большая вьюха. Почему-то изначальное состояние не соответствует верстки, а оказалось это где-то в коде прописано.


- Получается это всегда плохой вариант?
- Нет, когда у тебя верстка переиспользуется, то вариант допустимый

2022-12-08 08:00 UTC, Maksim2355 commented on base_feature/src/main/res/layout/layout_pagination_footer.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
Давно не видел relative в уличных гонках...

Лучше переписать. Для начала, на смену relative есть constraint, который более производительный. Плюс в этом кейсе вроде можно ограничится FrameLayout. Разве нет?

2022-12-08 08:00 UTC, Maksim2355 commented on f_films/src/main/java/ru/surfstudio/f_films/FilmsFragmentView.kt
> +                        UiState.Empty -> Unit
Не особо понял зачем нужен UiState.Empty.

2022-12-08 08:00 UTC, Maksim2355 commented on f_films/src/main/java/ru/surfstudio/f_films/FilmsViewModel.kt
> +    val favouritesFilms = filmsRepository.favouritesFilmListFlow
Переменная вроде не используется

2022-12-08 08:00 UTC, Maksim2355 commented on f_films/src/main/java/ru/surfstudio/f_films/FilmsViewModel.kt
> +        curPage++
Может вынести это в стейт?

2022-12-08 08:00 UTC, Maksim2355 commented on f_films/src/main/java/ru/surfstudio/f_films/FilmsFragmentView.kt
> +                        UiState.Empty -> Unit
Давай либо его выпилим полностью. Я так понимаю он у тебя выступает в качестве первоначальной загрузки. Если зайти в твою прилу без инета, то вот такой странный результат


<img width="1440" alt="Снимок экрана 2022-12-08 в 10 52 18" src="https://user-images.githubusercontent.com/47825674/206389928-b721c6c9-574c-4de0-a7e8-8583c2b6be2d.png">

2022-12-08 08:00 UTC, Maksim2355 commented on f_films/src/main/java/ru/surfstudio/f_films/FilmsViewModel.kt
> +                            }
Ты прям как банк. Тут есть определенно лишняя конвертация

Ты из filmUi мапишь в film и потом обратно в filmUi

Можно немного упростить

```kotlin

films = _screenState.value.films.map { filmUi ->
                            filmUi.copy(
                                isFavourite = filmsRepository.favouritesFilmListFlow.value.any { it.id == filmUi.film.id }
                            )
                        }

```
При желании можно еще упростить

2022-12-08 08:00 UTC, Maksim2355 commented on f_films/src/main/java/ru/surfstudio/f_films/FilmsViewModel.kt
> +                            }
На будущее. С серфа есть обертки. По типу selectableData/checkableData

2022-12-08 08:00 UTC, Maksim2355 commented on f_films/src/main/java/ru/surfstudio/f_films/FilmsViewModel.kt
> +                            }
включает в себя обертки и некоторые экстеншены

Не надо их подтягивать, просто знать что для таких кейсов они есть

2022-12-11 22:59 UTC, Pec3maker commented on f_films/src/main/java/ru/surfstudio/f_films/FilmsViewModel.kt
> +                            }
Просто хотел оправдать уже существующий маппер =)
![изображение](https://user-images.githubusercontent.com/38285312/206933917-3070c357-b800-4c38-87bd-314edc86dff2.png)

2022-12-12 08:40 UTC, Maksim2355 approved these changes

2022-12-12 08:40 UTC, Maksim2355 commented on f_films/src/main/java/ru/surfstudio/f_films/FilmsFragmentView.kt
> +                    }
Большая конструкция и лишний маппинг. Можно сократить

```kotlin
addAll(it.films, filmViewController)
```

Но можно сделать еще более кратко

```kotlin

easyAdapter.setData(
                        it.films,
                        filmViewController,
                        if (it.state is UiState.Success) PaginationState.READY else PaginationState.ERROR
                    )

2022-12-12 08:40 UTC, Maksim2355 commented on f_films/src/main/res/layout/fragment_films.xml
>  <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Для такой вертски лучше использовать более простые контейнеры, по типу FrameLayout

2022-12-12 09:52 UTC, Maksim2355 approved these changes

2022-12-12 09:52 UTC, merged